# ===============================
# Application
# ===============================
spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

# ===============================
# Database
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Mail (Gmail SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# RazorPay Payment Gateway
# ===============================
razorpay.api.key=${RAZORPAY_API_KEY}
razorpay.api.secret=${RAZORPAY_API_SECRET}
